<a href="https://colab.research.google.com/github/KINGSANGWOON/personal-study/blob/main/numpy(%EB%B3%B8%EB%AC%B81).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#라이브러리 불러오기 (라이브러리란 모듈.py의 집합이라고 볼 수 있다)
import numpy  as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
np.array((2,2))


array([2, 2])

In [ ]:
#numpy 를 사용하는 이유는 Python 에서는 배열 자료형을 지원하지 않기 때문에, numpy 와 같은 라이브러리를 사용한다 (배열 같은 타입을 가지는 데이터가 나열된 집합)

array1 = np.array([1,2,3])
print(np.shape(array1)) # shape는 차원을 알 수 있다


array2 = np.array([[1,2,3],[3,4,5]])
print(np.shape(array2))
# 1 2 3 
# 3 4 5 
# 즉 열이 2 줄 행이 3 개

array3 = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(np.shape(array3))
# 1 2 3
# 4 5 6 
# 뒤에 
# 7 8 9
# 10 11 12
# 첫번째 열 2 개 
# 두번째 열 2 개 
# 행의 갯수는 둘 다 3개

# 그냥 shape 에 나오는 갯수를 통해서 배열의 차원을 알 수 있다 예 ) 하나면 1 차원  등등 

(3,)
(2, 3)
(2, 2, 3)


In [ ]:
#numpy란 무엇인가
#다차원 배열을 쉽고 효율적으로 계산할 수 있도록 도와주는 것이다(배열의 연산을 하는 파이썬 대표 라이브러리)


list1 = [1,2,3]
np.array(list1)

array([1, 2, 3])

In [ ]:
# numpy의 자체 생성 함수 활용
print(np.array([1,2,3], dtype=int)) #dype 하면 배열의 타입을 정할 수 있다

print(np.array([1,2,3],dtype=float))

print(np.array([1,2,3], dtype=str)) # 출력의 U1은 유니코드 문자형을 말하는 것이므로 잘 출력이 되었음을 알 수 있다

print(np.array(['1','2','3'], dtype=int)) # string 도 int 자료형으로 해줄 수 있다

[1 2 3]
[1. 2. 3.]
['1' '2' '3']
[1 2 3]


In [ ]:
# 자체 생성 함수
print(np.ones((3,3),dtype=int)) # 3,3 이니까 2 차원 배열로 열3 행3 그리고 안의 값은 one 

print(np.zeros((4,4))) #기본적으로 실수형의 type 을 제공하는 것 같다


# 단위 행렬
print(np.eye(3,3)) # 수학적인 개념인데 아직은 단위 행렬 기능이구나 정도만 알아놓자
print(np.eye(4,4))

#사용자 지정 값
print(np.full((3,3),10))
print(np.full((3,3),80))

#랜덤 지정 값
np.random.rand(4,4) # 0부터 1까지 사이에 배열을 만들어 준다
np.random.rand(3,2)



[[1 1 1]
 [1 1 1]
 [1 1 1]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[[10 10 10]
 [10 10 10]
 [10 10 10]]
[[80 80 80]
 [80 80 80]
 [80 80 80]]


array([[0.10871937, 0.58551164],
       [0.10011638, 0.55181575],
       [0.49250026, 0.59765277]])

In [ ]:
# 동간격 배열 생성

print(np.arange(10)) # 0 ~ 10 까지의 배열을 만들어 준다

print(np.arange(2,10)) # 2 부터 10까지 만들어 준다

print(np.arange(2,10,2)) #2 부터 10까지 2씩 간격으로
print(np.arange(1,20,3)) 
print(np.arange(1,15))

np.linspace(2,10,3) # 1 부터 10 사이의 5개의 등간격을 가지고 싶다면 linspace를 쓰면 된다 
np.linspace(5,10,3)

[0 1 2 3 4 5 6 7 8 9]
[2 3 4 5 6 7 8 9]
[2 4 6 8]
[ 1  4  7 10 13 16 19]
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14]


array([ 5. ,  7.5, 10. ])

In [ ]:
#슬라이싱 (Slicing)

#arr[ 행(row) , 열(column) ]

arr1 = np.array([[1,2,3,4],
                [5,6,7,8],
                [9,10,11,12],
                 [13,14,15,16]])

print(arr1[0])
print(arr1[1])
print(arr1[2,:]) # 행 기준 슬라이싱
print(arr1[:,0]) # 열 기준 슬라이싱

print(arr1[::2]) # 간격을 지정해서 슬라이싱

print(arr1[1:3])
print(arr1[:,2:3])

print(arr1[:,-1])

print(arr1[0:2,2:4])

print(arr1[1:3,-1])

print(arr1[2:4,1:3])



[1 2 3 4]
[5 6 7 8]
[ 9 10 11 12]
[ 1  5  9 13]
[[ 1  2  3  4]
 [ 9 10 11 12]]
[[ 5  6  7  8]
 [ 9 10 11 12]]
[[ 3]
 [ 7]
 [11]
 [15]]
[ 4  8 12 16]
[[3 4]
 [7 8]]
[ 8 12]
[[10 11]
 [14 15]]


In [ ]:
#fancy  인덱싱 해당하는 위치의 값을 쏙 빼오는 것

print(arr1[3,3])  

print(arr1[[0,2],:])

print(arr1[[0,1,3],:])


print(arr1[:,[0,1,2]])

print(arr1[[0,1],[0,1]]) # 1 6이 나온다

print(arr1[[0,1],[2,3]]) # 3 8이 나온다



16
[[ 1  2  3  4]
 [ 9 10 11 12]]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [13 14 15 16]]
[[ 1  2  3]
 [ 5  6  7]
 [ 9 10 11]
 [13 14 15]]
[1 6]
[3 8]


In [ ]:
# Boolean 인덱싱


boolean1 = np.array([[True,True,True,True],[False,False,False,False],[True,True,True,True],[False,False,False,False]])

In [ ]:
print(arr1[boolean1]) # true인 값만 출력한다

# boolean 배열 생성
arr1 > 5 # 5 보다 큰 값들은 True 아닌 값들은 False의 값을 출력한다

print(arr1[arr1>10]) # arr1 에서 10 보다 큰 True 값들을 출력해준다는 뜻이다

print(arr1[arr1 < 4])

array([ 1,  2,  3,  4,  9, 10, 11, 12])

In [ ]:
# 유용한 numpy 함수

#최소값, 최대값
print(np.min(arr1),np.max(arr1))

#최소값 , 최대값의 인덱스
print(np.argmin(arr1),np.argmax(arr1))

#전체 합, 평균
print(np.sum(arr1), np.mean(arr1)) 

#특정 값의 인덱스
np.where(arr1==3)


1 16
0 15
136 8.5


(array([0]), array([2]))

In [ ]:
#배열 차원 변환 reshape로 차원을 변환할 수 있다

arr2 = np.arange(10) # 1 차원 배열을 만들어 줬다

arr3 = arr2.reshape(2,5) # 2차원으로 변경이 가능하다 참고로 변환 하는 차원도 값이 맞아야 한다 그렇지 않으면 에러가 난다 예 10개의 index 가 있는데 reshape(2,4) 2개의 행과 4개의 열을 하면 모든 수가 들어 갈 수 없어 에러 발생한다

print(arr3)
print(np.shape(arr3))

arr4 = arr2.reshape(2,-1) # -1을 쓰면 자동적으로 나눠주기도 한다
print(arr4) 


[[0 1 2 3 4]
 [5 6 7 8 9]]
(2, 5)
[[0 1 2 3 4]
 [5 6 7 8 9]]


In [ ]:
#정렬(sort) 기본적으로 오름차순이고 -1을 추가하면 내림차순으로 바뀐다

TestArr = np.array([2,1,8,4,9,2,3,7,5])

print(np.sort(TestArr))
print(np.sort(TestArr)[::-1])


# N 차원 정렬

NTestArr = np.array([[33,22,66,33],[12,54,56,23],[43,45,87,12],[34,76,55,45]])

print(np.sort(NTestArr,axis=0)) # 행 방향 정렬

np.sort(NTestArr,axis=0)[::-1] # 행 방향 내림차순 정렬

print(np.sort(NTestArr,axis=1)) # 열 방향은 axis에 값을 1을 넣어주면 된다

print(np.sort(NTestArr,axis=1)[::-1])


[1 2 2 3 4 5 7 8 9]
[9 8 7 5 4 3 2 2 1]
[[12 22 55 12]
 [33 45 56 23]
 [34 54 66 33]
 [43 76 87 45]]
[[22 33 33 66]
 [12 23 54 56]
 [12 43 45 87]
 [34 45 55 76]]
[[34 45 55 76]
 [12 43 45 87]
 [12 23 54 56]
 [22 33 33 66]]
