<a href="https://colab.research.google.com/github/KINGSANGWOON/personal-study/blob/main/numpy(%EB%B3%B8%EB%AC%B82).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
#행렬 (행과 열로 이루어진 2차원 배열을 행렬이라고 한다) 2차원 배열
#행렬의 차원이 같아야 연산이 가능하다
#같은 위치에서의 연산은 Element-wise 연산이라고 한다(두 행렬의 차원이 같아야함)
#내적 연산(Dot Product): 연산되는 앞행렬(열)과 뒤행렬(행) 차원이 같아야합니다 예) 2행 3열의 배열에서 3행 2 열의 값을 계산할 수 있다
import numpy as np

arr1 = np.array([[1,2,3,4],
                [5,6,7,8,],
                [9,10,11,12],
                 [13,14,15,16]])

arr2 = np.array([[1,2,3,4],
                [5,6,7,8,],
                [9,10,11,12],
                 [13,14,15,16]])

print(arr1 + arr2)

np.shape(arr1) , np.shape(arr2) #Element-wize




[[ 2  4  6  8]
 [10 12 14 16]
 [18 20 22 24]
 [26 28 30 32]]


((4, 4), (4, 4))

In [3]:
#Dot Product

np.dot(arr1,arr2) # 90이 나온 이유 1 * 1 + 2*5 + 3* 9 + 4* 13
                  # 1*2 + 2*6 + 3*10 + 4*14 = 100
                  # 1*3 + 2*7 + 3*11 + 4*15 = 110 
                  

array([[ 90, 100, 110, 120],
       [202, 228, 254, 280],
       [314, 356, 398, 440],
       [426, 484, 542, 600]])

In [5]:
arr3 = np.array([[1,2,3,4],[5,6,7,8]])
arr4 = np.array([[1,2],[5,6],[9,10],[13,14]])

In [6]:
np.dot(arr3,arr4)

array([[ 90, 100],
       [202, 228]])

In [8]:
# BroadCasting 연산
# 저차원 배열의 연산을 고차원 배열로 확장시키는 것을 의미합니다

arr3d = np.array([[[0,1],[2,3],[4,5],[6,7]],[[8,9],[10,11],[12,13],[14,15]],[[16,17],[18,19],[20,21],[22,23]]])
arr2d = np.array([[0,1],[2,3],[4,5],[6,7]])


np.shape(arr3d) , np.shape(arr2d)

((3, 4, 2), (4, 2))

In [10]:
print(arr3d + arr2d)

print(arr2d * 10)


[[[ 0  2]
  [ 4  6]
  [ 8 10]
  [12 14]]

 [[ 8 10]
  [12 14]
  [16 18]
  [20 22]]

 [[16 18]
  [20 22]
  [24 26]
  [28 30]]]
[[ 0 10]
 [20 30]
 [40 50]
 [60 70]]
